### ISSUE TITLE
Lualine theme not applied

### ISSUE THREAD

**Issue by mohvn** [datsfilipe/min-theme.nvim#7]
It seems like lualine theme is not applying, cause it's not the same as the example

### Lualine with different colors
![screenshot png-shadow](https://github.com/datsfilipe/min-theme.nvim/assets/57570197/21dfd21d-0818-4ae1-93e2-ac227490fbd8)

### Your Lualine in preview image
![image](https://github.com/datsfilipe/min-theme.nvim/assets/57570197/bc449170-dce7-4079-8d8d-126f252fe8e7)

my config file:

```lua
require('min-theme').setup({
  -- (note: if your configuration sets vim.o.background the following option will do nothing!)
  theme = 'dark',      -- String: 'dark' or 'light', determines the colorscheme used
  transparent = false, -- Boolean: Sets the background to transparent
  italics = {
    comments = true,   -- Boolean: Italicizes comments
    keywords = true,   -- Boolean: Italicizes keywords
    functions = true,  -- Boolean: Italicizes functions
    strings = true,    -- Boolean: Italicizes strings
    variables = true,  -- Boolean: Italicizes variables
  },
  overrides = {},      -- A dictionary of group names, can be a function returning a dictionary or a table.
})

require('lualine').setup {}

vim.cmd.colorscheme('min-theme')
```

**Comment by datsfilipe** [comment]
Hi! the `lualine` theme is correct in your screenshot, the problem is the outdated preview image (mb!)
